services:
    # nginx
    web:
        build:
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            # target: "app_dev"
            target: "${BUILD_TARGET:-app}" # this will read from the env file
        volumes:
            #- /var/www/html/vendor 
            - ./app:/var/www/html
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            MYSQL_HOST: db   # here we use the service name 
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            REDIS_HOST: cache  # name of the service
            REDIS_PORT: ${REDIS_PORT}
            # See https://xdebug.org/docs/all_settings#mode
            # XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            XDEBUG_MODE: debug # turns it on
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        # environment:
        #     MYSQL_ROOT_PASSWORD: secret
        #     #MYSQL_PORT: 3306
        #     MYSQL_USER: user
        #     MYSQL_PASSWORD: secret
        #     MYSQL_DATABASE: docker-php

    # redis
    cache:
        image: redis:latest

volumes:
    mysqldata:  #docker will alocate space for it

